# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

default: &default
  docker:
    - image: circleci/ruby:2.5.0
  working_directory: ~/app

save_bundle_cache_option: &save_bundle_cache_option
  key: v1-bundle-{{ checksum "itamae-plugin-recipe-tmux.gemspec" }}
  paths:
    - ~/app/vendor/bundle

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v1-bundle-{{ checksum "itamae-plugin-recipe-tmux.gemspec" }}
    - v1-bundle

build: &build
  <<: *default

  steps:
    - checkout

    # Setup Docker
    - setup_remote_docker
    - restore_cache:
        keys:
          - v1-{{ .Environment.CIRCLE_JOB }}
        paths:
          - /caches/image.tar
    - run:
        name: Load Docker image layer cache
        command: |
          set +o pipefail
          docker load -i /caches/image.tar | true

    - restore_cache:
        <<: *restore_bundle_cache_option
    - run: ./.circleci/setup_bundle.sh
    - save_cache:
        <<: *save_bundle_cache_option

    - run: bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=$CIRCLE_JOB --tag itamae-plugin:latest

    - save_cache:
        key: v1-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
        paths:
          - /caches/image.tar

    - run: DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec

jobs:
  centos:7:
    <<: *build

  debian:jessie:
    <<: *build

build_jobs: &build_jobs
  - centos:7
  - debian:jessie

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
