version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.5.0
    working_directory: ~/app

commands:
  setup_bundle:
    description: "Setup bundle with cache"
    steps:
      - restore_cache:
          keys:
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itamae-plugin-recipe-tmux.gemspec" }}
            - v1-bundle-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: bundle install
          command: |
            set -xe
            bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean
      - save_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_JOB }}-{{ checksum "itamae-plugin-recipe-tmux.gemspec" }}
          paths:
            - ~/app/vendor/bundle
            - ~/app/Gemfile.lock

jobs:
  build:
    parameters:
      image:
        type: string

    executor:
      name: default

    steps:
      - checkout

      # Setup Docker
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Environment.CIRCLE_JOB }}
          paths:
            - /caches/image.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image.tar | true

      - setup_bundle

      - run: bundle exec itamae docker --node-yaml=recipes/node.yml recipes/install.rb --image=<< parameters.image >> --tag itamae-plugin:latest

      - save_cache:
          key: v1-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - /caches/image.tar

      - run: DOCKER_IMAGE=itamae-plugin:latest bundle exec rspec

build_jobs: &build_jobs
  - build:
      name:  centos:7
      image: centos:7
  - build:
      name:  debian:jessie
      image: debian:jessie

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
